const vscode = require('vscode');
const assert = require('node:assert/strict');
const { readFileSync, writeFileSync } = require('node:fs');
const { join } = require('node:path');

exports.run = async () => {
  const results = [];
  const root = vscode.workspace.workspaceFolders[0].uri.fsPath;
  const extension = vscode.extensions.getExtension('windflowing.humanflow');
  // 路径设置是 machine 作用域；必须确认隔离用户配置生效，禁止回退到真实 CLI。
  assert.equal(vscode.workspace.getConfiguration('humanflow').get('codexJsPath'), join(extension.extensionPath, 'tests/fixtures/fake-codex.cjs'));
  const api = await extension.activate();
  const dispatch = api.dispatch;
  const record = name => { results.push(name); console.log('PASS: ' + name); };
  try {
    if (process.env.HUMANFLOW_TEST_PHASE === 'restore') {
      const previous = JSON.parse(readFileSync(process.env.HUMANFLOW_TEST_REPORT, 'utf8'));
      assert.equal(api.snapshot().task.id, previous.taskId);
      assert.equal(api.snapshot().history.length, previous.historyLength);
      assert.ok(api.snapshot().task.outcomes.length);
      assert.ok(api.snapshot().task.findings.length);
      assert.equal(api.snapshot().suggestion, null);
      assert.equal(api.snapshot().task.draft, '重启后继续的草稿');
      assert.equal(api.snapshot().task.uiState.view, 'changes');
      previous.passed.push('真实扩展进程重启后恢复讨论、应用记录和问题列表，旧候选不可应用');
      writeFileSync(process.env.HUMANFLOW_TEST_REPORT, JSON.stringify(previous, null, 2));
      return;
    }
    await vscode.commands.executeCommand('humanflow.open');
    await dispatch({ type: 'ask', question: 'initial' });
    let state = api.snapshot();
    assert.ok(state.suggestion, state.status);
    assert.equal(state.task.focus, null);
    record('无选区创建项目任务并通过真实 stdio 客户端收到跨文件候选');
    const originalTask = state.task.id;
    await dispatch({ type: 'apply', batchId: state.suggestion.batchId, selection: [[0], []] });
    assert.equal(readFileSync(join(root, 'a.js'), 'utf8'), 'const a = 2;\nconst c = 1;\n');
    assert.equal(readFileSync(join(root, 'b.js'), 'utf8'), 'const b = 1;\n');
    assert.equal(api.snapshot().suggestion, null);
    record('真实 WorkspaceEdit 部分应用并保存，未选择片段与文件保持原样');
    const doc = await vscode.workspace.openTextDocument(vscode.Uri.file(join(root, 'a.js')));
    await vscode.window.showTextDocument(doc);
    await vscode.commands.executeCommand('undo');
    assert.equal(doc.getText(), 'const a = 1;\nconst c = 1;\n');
    record('编辑器撤销可恢复应用前内容');
    const edit = new vscode.WorkspaceEdit();
    edit.replace(doc.uri, new vscode.Range(0, 0, 0, doc.lineAt(0).text.length), 'const a = 9;');
    await vscode.workspace.applyEdit(edit);
    await dispatch({ type: 'bind' });
    assert.equal(api.snapshot().task.id, originalTask);
    await dispatch({ type: 'ask', question: 'followup' });
    assert.ok(api.snapshot().suggestion, api.snapshot().status);
    record('手动编辑与切换关注点后保留任务，追问收到接受/未接受结果及未保存缓冲区');
    await dispatch({ type: 'ask', question: 'initial' });
    const staleId = api.snapshot().suggestion.batchId;
    const userEdit = new vscode.WorkspaceEdit();
    userEdit.insert(doc.uri, new vscode.Position(0, 0), '// 人工修改\n');
    await vscode.workspace.applyEdit(userEdit);
    await dispatch({ type: 'apply', batchId: staleId, selection: [[0], []] });
    assert.ok(doc.getText().startsWith('// 人工修改'));
    assert.equal(api.snapshot().suggestion, null);
    record('用户编辑使旧批次失效，旧应用请求不能覆盖新代码');
    const pending = dispatch({ type: 'ask', question: 'wait' });
    await new Promise(resolve => setTimeout(resolve, 150));
    await dispatch({ type: 'cancel' }); await pending;
    assert.match(api.snapshot().status, /取消/);
    assert.equal(api.snapshot().task.id, originalTask);
    record('取消请求保留讨论并结束等待');
    await doc.save();
    await api.flush();
    // 此处验证面板重开；扩展进程重启恢复另由离线控制器测试覆盖。
    const historyLength = api.snapshot().history.length;
    await vscode.commands.executeCommand('workbench.action.closeAllEditors');
    await vscode.commands.executeCommand('humanflow.open');
    assert.equal(api.snapshot().task.id, originalTask);
    assert.equal(api.snapshot().history.length, historyLength);
    record('关闭并重开面板保留任务与讨论');
    await dispatch({ type: 'ask', question: 'audit' });
    assert.ok(api.snapshot().task.findings.length);
    const findingId = api.snapshot().task.findings[0].id;
    await dispatch({ type: 'findingStatus', id: findingId, status: 'deferred' });
    await dispatch({ type: 'fixFinding', id: findingId });
    state = api.snapshot();
    assert.ok(state.suggestion.changes.length, state.status);
    assert.equal(state.suggestion.findingId, findingId);
    record('项目问题可单独处理，保留人工状态并绑定候选批次');
    await dispatch({ type: 'review', batchId: state.suggestion.batchId, selection: [[0], []], model: 'offline-review', effort: 'low' });
    assert.equal(api.snapshot().suggestion.review.model, 'offline-review');
    assert.deepEqual(api.snapshot().suggestion.changes, state.suggestion.changes);
    record('第二模型仅审查勾选结果，原候选未被修改');
    await dispatch({ type: 'editDraft', index: 0, batchId: state.suggestion.batchId });
    const draft = vscode.window.activeTextEditor.document;
    assert.equal(draft.uri.scheme, 'untitled');
    const draftEdit = new vscode.WorkspaceEdit();
    draftEdit.insert(draft.uri, new vscode.Position(0, 0), '// draft change\n');
    await vscode.workspace.applyEdit(draftEdit);
    await dispatch({ type: 'useDraft', index: 0, batchId: state.suggestion.batchId });
    state = api.snapshot();
    assert.ok(state.suggestion.changes[0].edits[0].after.startsWith('// draft change'));
    assert.equal(state.suggestion.changes[0].edits.length, 1);
    await dispatch({ type: 'apply', batchId: state.suggestion.batchId, selection: [[0], []] });
    assert.ok(readFileSync(join(root, 'a.js'), 'utf8').startsWith('// draft change'));
    assert.equal(api.snapshot().task.findings[0].status, 'pendingVerification');
    record('草稿独立编辑后采用，实际应用一致；问题保留待验证状态');
    await dispatch({ type: 'ask', question: 'create' });
    state = api.snapshot();
    await dispatch({ type: 'apply', batchId: state.suggestion.batchId, selection: [[0]] });
    assert.equal(readFileSync(join(root, 'new.js'), 'utf8'), 'export const created = true;\n');
    record('新增文件经勾选后创建并保存');
    const { runValidation } = require(join(extension.extensionPath, 'src/vscode/validation.cjs'));
    // 仅测试固定无副作用命令；替代确认对话框，实际执行仍走真实 Tasks API。
    const testVscode = { workspace: vscode.workspace, tasks: vscode.tasks, Task: vscode.Task, ShellExecution: vscode.ShellExecution,
      TaskRevealKind: vscode.TaskRevealKind, TaskPanelKind: vscode.TaskPanelKind, window: { showWarningMessage: async () => '运行' } };
    const validation = await runValidation(testVscode, root, { command: 'echo HumanFlow-validation', reason: '宿主集成测试' }, () => {});
    assert.equal(validation.exitCode, 0);
    record('真实 VS Code 任务执行固定验证命令并捕获退出码');
    await dispatch({ type: 'provider', provider: 'deepseek' });
    assert.equal(api.snapshot().task.provider, 'deepseek');
    assert.equal(api.snapshot().suggestion, null);
    await dispatch({ type: 'ask', question: 'audit' });
    assert.equal(api.snapshot().suggestion.requestedModel, 'deepseek-flash');
    assert.equal(api.snapshot().suggestion.provider, 'deepseek');
    assert.equal(api.snapshot().task.id, originalTask);
    await dispatch({ type: 'provider', provider: 'codex' });
    await dispatch({ type: 'ask', question: 'audit' });
    assert.equal(api.snapshot().suggestion.requestedModel, 'offline-test');
    record('提供方切换保留任务、作废旧候选，模型目录与请求按服务隔离');
    await dispatch({ type: 'taskSettings', goal: '保持公共接口', budget: { paths: [], files: 12, added: 1000, removed: 1000 }, threadMode: 'continuous' });
    await dispatch({ type: 'ask', question: 'audit' });
    await dispatch({ type: 'ask', question: 'audit' });
    assert.equal(api.snapshot().task.contextDetails.thread, '复用 / 恢复');
    await dispatch({ type: 'compact' });
    assert.equal(api.snapshot().task.harness.compaction, '已压缩');
    await dispatch({ type: 'draft', taskId: originalTask, text: '重启后继续的草稿' });
    await dispatch({ type: 'uiState', taskId: originalTask, value: { view: 'changes', scroll: { discuss: 200 } } });
    record('宿主持续线程复用、压缩事件、草稿和阅读状态持久化（模型为协议替身）');
    // 关闭测试草稿时丢弃，不影响已验证的业务文件。
    await vscode.window.showTextDocument(draft);
    await vscode.commands.executeCommand('workbench.action.revertAndCloseActiveEditor');
    await api.flush();
    writeFileSync(process.env.HUMANFLOW_TEST_REPORT, JSON.stringify({ passed: results, taskId: originalTask, historyLength: api.snapshot().history.length }, null, 2));
  } catch (error) {
    writeFileSync(process.env.HUMANFLOW_TEST_REPORT, JSON.stringify({ passed: results, error: error.stack }, null, 2));
    throw error;
  }
};
